version: '2'

services:
  redis:
    image: redis
  jonggrang_ai_api:
    build: .
    command: unicorn
    volumes:
      - .:/jonggrang_ai
    ports:
      - "80:3000"
    depends_on:
      - redis
    env_file:
      - .env
  