source 'https://rubygems.org'


gem 'rails', '4.2.7.1'
gem 'sdoc', '~> 0.4.0', group: :doc

# DB for caching and save data
gem 'redis', '3.3'

# Load .env for parsing secret environment
gem 'dotenv', '2.1.2'

# Slack incoming webhook 
gem 'slack-notifier', '2.0'

# SMS and Phone third party
gem 'nexmo', '~> 4.5'

# Libcurl
gem 'curb', '~> 0.9.3'

# Use Unicorn as the app server
gem 'unicorn'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
end

